"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.7.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-dx@f1ni9*w1rc33k_0^8v#$c9hpf3k_m9v-w%7j!w$^)q==pa0'

DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 생성하신 앱
    'board',
    
    # django-allauth 및 소셜 로그인 필수 앱
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.kakao', # 카카오 프로바이더
]

SITE_ID = 1

# 로그인 / 로그아웃 후 이동할 URL 설정
LOGIN_REDIRECT_URL = '/board/'      # 로그인 성공 후 이동할 페이지
LOGOUT_REDIRECT_URL = '/board/'     # 로그아웃 후 이동할 페이지
LOGIN_URL = '/accounts/login/'      # @login_required 시 이동할 로그인 페이지

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # allauth 필수 미들웨어
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # 또는 os.path.join(BASE_DIR, 'templates')
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

# settings.py 맨 아래 추가

SOCIALACCOUNT_PROVIDERS = {
    'kakao': {
        'APP': {
            'client_id': 'f5797aa27145b4c698e9a298090a5cbf',  # 카카오 REST API 키
            'secret': 'ddvavlm8CVZwZZMyz1JqvJ5Lvr5cpvkS',                                    # Client Secret (없다면 빈 문자열)
            'key': '',
        }
    }
}

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'python_db',         # MariaDB 데이터베이스명
        'USER': 'root',              # MariaDB 계정
        'PASSWORD': 'totoro',        # MariaDB 비밀번호
        'HOST': 'localhost',         # 서버 주소
        'PORT': '3306',              # 서버 포트
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization (한국 환경 설정)
LANGUAGE_CODE = 'ko-kr'              # 한국어로 변경

TIME_ZONE = 'Asia/Seoul'             # 한국 시간대로 변경

USE_I18N = True

USE_TZ = True                        # DB 타임존 지원 (Asia/Seoul 기반으로 동작)


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'


# 🟡 django-allauth 상세 설정 (카카오 및 소셜 로그인 관련)
ACCOUNT_EMAIL_REQUIRED = False       # 이메일 필수 여부 (카카오 동의항목에 따라 조정)
ACCOUNT_USERNAME_REQUIRED = True     # 유저네임 필수 여부
ACCOUNT_EMAIL_VERIFICATION = 'none'  # 이메일 인증 절차 생략

SOCIALACCOUNT_AUTO_SIGNUP = True     # 소셜 로그인 시 추가 가입 폼 없이 즉시 가입
SOCIALACCOUNT_STORE_TOKENS = True    # access_token 저장 여부

# 🟢 터미널 실시간 SQL 쿼리 로깅
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}